title: Site
columns:
  # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
  - width: 1/3
    sections:
      galleries:
        type: pages
        headline: Campaign Image Galleries
        parent: kirby.page("galleries")
        template:
          - gallery
        info: "{{ page.images.count }} image(s)"
        layout: cardlets
        empty: No galleries yet
        image:
          cover: true
          query: page.previewImage
      video-galleries:
        type: pages
        headline: Campaign Video Galleries
        parent: kirby.page("videogalleries")
        template:
          - videogallery
        info: "{{ page.videos.count }} video(s)"
        layout: cardlets
        empty: No galleries yet
      slideshows:
        layout: list
        type: pages
        headline: Campaign Slideshows
        parent: kirby.page("slideshows")
        template:
          - slideshow
      webslides:
        layout: list
        type: pages
        headline: Campaign Web Slides
        parent: kirby.page("web-slides")
        template:
          - events
          - goal
          - goal2
          - error-slide
      opac:
        layout: list
        type: pages
        headline: OPAC Pages
        parent: kirby.page("opac")
        template:
          - opac
        image:
          cover: true
          query: page.previewImage

  # The second column
  - width: 2/3
    label: Links
    type: structure
    fields:
      docs:
        type: info
        label: Documentation
        text: |
          Please check out the following information for details on how to use this site: 
          * (link: https://github.com/salinapl/LibraryDigitalSignage text: Github Page)
          * (link: # text: Internal Library Documentation)
      otherlinks:
        extends: fields/links
        label: Other/Misc Links
      tags:
        label: Set Valid Campaign Categories
        type: tags
